[project]
name = "luckylinks"
version = "0.1.0"
description = "A telegram bot to randomly pick a saved link."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.11.3",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
]
